import { motion } from "framer-motion";
import { FileText, ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router-dom";

const TermsOfService = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <div className="pt-6 pb-24 px-4 max-w-3xl mx-auto">
        <motion.button
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          onClick={() => navigate(-1)}
          className="flex items-center gap-1.5 text-[13px] text-muted-foreground hover:text-foreground transition-colors mb-6"
        >
          <ArrowLeft size={14} />
          Back
        </motion.button>

        <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="mb-6">
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center">
              <FileText size={20} className="text-primary" />
            </div>
            <div>
              <h1 className="text-[22px] font-semibold text-foreground tracking-tight">Terms of Service</h1>
              <p className="text-[12px] text-muted-foreground">Version 1.0 · Effective 14 April 2026 · Last updated 14 April 2026</p>
            </div>
          </div>
        </motion.div>

        <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }} className="bg-primary/5 border border-primary/20 rounded-2xl p-5 mb-6">
          <p className="text-[14px] text-foreground/80 leading-relaxed">
            These Terms of Service (&ldquo;Terms&rdquo;) govern your use of Seven Mynd, a cognitive continuity platform operated by Abraham Osemudiameh, trading as Seven Mynd (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;). By creating an account or using Seven Mynd, you agree to these Terms. If you do not agree, do not use the service.
          </p>
        </motion.div>

        <div className="flex flex-col gap-5">
          <TermsSection index={0} title="1. The Service" paragraphs={[
            "Seven Mynd is a cognitive continuity system that remembers your conversations, tracks your decisions, detects behavioural patterns, and provides personalised AI-powered assistance across sessions. It is designed to help you make better decisions over time by maintaining a persistent understanding of your identity, history, and goals.",
            "Seven Mynd is an AI assistant. It is not a human. Its responses are generated by artificial intelligence and should not be treated as professional advice — including legal, financial, medical, therapeutic, or investment advice. You are solely responsible for decisions you make based on Seven Mynd's output.",
          ]} />

          <TermsSection index={1} title="2. Eligibility" paragraphs={[
            "You must be at least 16 years old to use Seven Mynd. By creating an account, you confirm that you are at least 16 years of age.",
            "If you are under 18, you confirm that you have the consent of a parent or legal guardian to use the service.",
          ]} />

          <TermsSection index={2} title="3. Your Account" paragraphs={[
            "You are responsible for maintaining the security of your account credentials. Do not share your password or allow others to access your account.",
            "You are responsible for all activity that occurs under your account. If you become aware of any unauthorised access, notify us immediately at hello@sevenmynd.com.",
            "We reserve the right to suspend or terminate accounts that violate these Terms, are used for fraudulent purposes, or pose a risk to other users or the service.",
          ]} />

          <TermsSection index={3} title="4. Your Data" paragraphs={[
            "You retain ownership of all content you provide to Seven Mynd, including messages, decisions, documents, and voice transcripts. We do not claim ownership of your data.",
            "You grant us a limited, non-exclusive licence to process your data solely for the purpose of providing the Seven Mynd service — including AI processing, memory storage, pattern detection, and decision tracking. This licence terminates when you delete your account.",
            "We process your data in accordance with our Privacy Policy, available at sevenmynd.com/privacy. The Privacy Policy forms part of these Terms.",
            "You can export all your data at any time from Settings. You can delete all your data at any time by deleting your account from Settings. Deletion is permanent and irreversible.",
          ]} />

          <TermsSection index={4} title="5. Acceptable Use" paragraphs={["You agree not to use Seven Mynd to:"]} listItems={[
            "Violate any applicable law, regulation, or third-party rights",
            "Upload malicious files, viruses, or harmful content",
            "Attempt to access other users' data or accounts",
            "Circumvent security measures, rate limits, or usage caps",
            "Use the service for spam, phishing, or social engineering",
            "Generate content that is illegal, abusive, harassing, or threatening",
            "Reverse engineer, decompile, or extract the source code of Seven Mynd",
            "Resell, sublicence, or commercially redistribute access to the service",
            "Use automated tools (bots, scrapers) to access the service without permission",
            "Impersonate another person or misrepresent your identity",
          ]} afterList="We reserve the right to suspend or terminate your account if you violate these terms, with or without notice depending on the severity of the violation." />

          <TermsSection index={5} title="6. AI-Generated Content" paragraphs={["Seven Mynd uses artificial intelligence to generate responses, detect patterns, and provide recommendations. You acknowledge and agree that:"]} listItems={[
            "AI responses may be inaccurate, incomplete, or inappropriate despite our best efforts",
            "Pattern detection and behavioural warnings are based on statistical analysis and may not always be correct",
            "Seven Mynd is not a substitute for professional advice — legal, financial, medical, therapeutic, or otherwise",
            "You are solely responsible for any actions you take based on Seven Mynd's output",
            "We do not guarantee the accuracy, reliability, or completeness of any AI-generated content",
          ]} />

          <TermsSection index={6} title="7. Governed Execution Layer (GEL)" paragraphs={["Seven Mynd can execute actions on your behalf, such as sending emails via Gmail, creating calendar events, or setting reminders. You acknowledge and agree that:"]} listItems={[
            "Every action requires your explicit approval before execution — Seven Mynd never acts without your confirmation",
            "You are responsible for reviewing the content of any action (such as an email draft) before approving it",
            "Once you approve and an action is executed, it cannot always be undone (for example, a sent email cannot be unsent)",
            "We are not liable for the consequences of actions you approve and execute through Seven Mynd",
            "You can revoke GEL permissions (Gmail, Calendar) at any time from Settings",
          ]} />

          <TermsSection index={7} title="8. Subscription and Payment" paragraphs={[
            "Seven Mynd offers a free beta period with full access to all features. After the beta period, a paid subscription may be required to continue using the service.",
            "Subscription plans and pricing will be displayed on the subscription page within the app when available. All prices will include VAT where applicable.",
            "Payments will be processed securely through Stripe. We do not store your payment card details.",
            "We reserve the right to change subscription pricing with at least 30 days' notice. Price changes do not affect your current billing period.",
          ]} />

          <TermsSection index={8} title="9. Service Availability" paragraphs={[
            "We aim to provide Seven Mynd with high availability but do not guarantee uninterrupted service. The service may be temporarily unavailable due to maintenance, updates, or circumstances beyond our control.",
            "We will make reasonable efforts to notify you of planned maintenance in advance.",
            "We are not liable for any loss or damage arising from service interruptions, downtime, or data processing delays.",
          ]} />

          <TermsSection index={9} title="10. Intellectual Property" paragraphs={[
            "Seven Mynd, including its name, logo, design, code, architecture, and documentation, is the intellectual property of Abraham Osemudiameh, trading as Seven Mynd. All rights reserved.",
            "Your data remains yours. Our intellectual property remains ours. These Terms do not transfer any intellectual property rights to either party beyond the limited licences described herein.",
          ]} />

          <TermsSection index={10} title="11. Limitation of Liability" paragraphs={["To the maximum extent permitted by law:"]} listItems={[
            "Seven Mynd is provided \"as is\" and \"as available\" without warranties of any kind, express or implied",
            "We do not warrant that the service will be error-free, uninterrupted, or free of harmful components",
            "We are not liable for any indirect, incidental, consequential, or punitive damages arising from your use of Seven Mynd",
            "Our total liability to you for any claim arising from these Terms or your use of the service is limited to the amount you paid us in the 12 months preceding the claim, or £100, whichever is greater",
            "Nothing in these Terms excludes or limits our liability for death or personal injury caused by our negligence, fraud, or any other liability that cannot be excluded by law",
          ]} />

          <TermsSection index={11} title="12. Indemnification" paragraphs={[
            "You agree to indemnify and hold us harmless from any claims, damages, losses, or expenses (including reasonable legal fees) arising from your violation of these Terms, your use of the service, or your violation of any third-party rights.",
          ]} />

          <TermsSection index={12} title="13. Termination" paragraphs={[
            "You may terminate your account at any time by deleting it from Settings. Upon deletion, all your personal data is permanently removed within 30 days as described in our Privacy Policy.",
            "We may terminate or suspend your account if you materially breach these Terms. Where possible, we will provide notice and an opportunity to remedy the breach before termination.",
            "Upon termination, your right to use the service ceases immediately. Sections of these Terms that by their nature should survive termination (including intellectual property, limitation of liability, and indemnification) will continue to apply.",
          ]} />

          <TermsSection index={13} title="14. Changes to These Terms" paragraphs={[
            "We may update these Terms from time to time. We will notify you by email at least 30 days before material changes take effect.",
            "If you do not agree to the updated Terms, you may delete your account before the changes take effect. Continued use of Seven Mynd after the effective date constitutes acceptance of the updated Terms.",
          ]} />

          <TermsSection index={14} title="15. Governing Law and Disputes" paragraphs={[
            "These Terms are governed by the laws of England and Wales.",
            "Any disputes arising from these Terms or your use of Seven Mynd will be subject to the exclusive jurisdiction of the courts of England and Wales.",
            "If any provision of these Terms is found to be unenforceable, the remaining provisions will continue in full force and effect.",
          ]} />

          <TermsSection index={15} title="16. Contact" paragraphs={[
            "For questions about these Terms, contact us at hello@sevenmynd.com.",
            "For data protection and privacy enquiries, contact privacy@sevenmynd.com.",
          ]} />
        </div>

        <p className="text-[11px] text-muted-foreground text-center mt-6 leading-relaxed">
          Seven Mynd Terms of Service · Version 1.0 · 14 April 2026
          <br />
          Abraham Osemudiameh, trading as Seven Mynd · sevenmynd.com
        </p>
      </div>
    </div>
  );
};

const TermsSection = ({ index, title, paragraphs, listItems, afterList }: {
  index: number; title: string; paragraphs: string[]; listItems?: string[]; afterList?: string;
}) => (
  <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.08 + index * 0.03 }} className="bg-card border border-border rounded-2xl p-5">
    <h2 className="text-[15px] font-medium text-foreground mb-3">{title}</h2>
    {paragraphs.map((p, i) => (
      <p key={i} className="text-[13px] text-foreground/80 leading-relaxed mb-2">{p}</p>
    ))}
    {listItems && (
      <div className="flex flex-col gap-1.5 mt-1">
        {listItems.map((item, j) => (
          <div key={j} className="flex items-start gap-2">
            <div className="w-1 h-1 rounded-full bg-muted-foreground mt-2 shrink-0" />
            <span className="text-[13px] text-foreground/80 leading-relaxed">{item}</span>
          </div>
        ))}
      </div>
    )}
    {afterList && <p className="text-[13px] text-foreground/80 leading-relaxed mt-3">{afterList}</p>}
  </motion.div>
);

export default TermsOfService;
